apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: {{ .Values.nodeEnv | default "production" | quote }}
  MONGO_CLUSTER: {{ .Values.secrets.mongoCluster | quote }}
  MONGO_DBNAME: {{ .Values.secrets.mongoDbname | quote }}
