apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: {{ .Values.images.product }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 9000
        envFrom:
        - secretRef:
            name: app-secrets
        - configMapRef:
            name: app-config
